d = int(input("Enter The First Day : "))
m = int(input("Enter The First Month : "))
y = int(input("Enter The First year : "))
dd = int(input("Enter The Second Day : "))
mm = int(input("Enter The Second Day : "))
yy = int(input("Enter The Second Day : "))
print(abs(dd-d),"Day",abs(mm-m),"Month",abs(yy-y),"Year")